services:
  redis-stack-server:
    image: docker.io/redis/redis-stack-server:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/redis-stack.conf

  line-webhook:
    image: line-webhook:latest
    ports:
      - "${WEBHOOK_PORT}:${WEBHOOK_PORT}"
    volumes:
      - ./logs:/home/myuser/src/logs
      - ./redis-data/tls:/home/myuser/src/tls
    user: "root:root"
    environment:
      WEBHOOK_HOST: ${WEBHOOK_HOST}
      WEBHOOK_PORT: ${WEBHOOK_PORT}
      WEBHOOK_WORKERS: ${WEBHOOK_WORKERS}
      WEBHOOK_THREADS: ${WEBHOOK_THREADS}
      CHANNEL_ACCESS_TOKEN: ${CHANNEL_ACCESS_TOKEN}
      CHANNEL_SECRET: ${CHANNEL_SECRET}
      REDIS_HOST: redis-stack-server
      REDIS_PORT: ${REDIS_PORT}
      REDIS_ADMIN: ${REDIS_ADMIN}
      REDIS_ADMIN_PASSWORD: ${REDIS_ADMIN_PASSWORD}
      SERVER_HOST: ${SERVER_HOST}
      HISTORY_DIALOGUE_PORT: ${HISTORY_DIALOGUE_PORT}
      DETECT_INTENT_PORT: ${DETECT_INTENT_PORT}
      INFORMATION_RETRIEVAL_PORT: ${INFORMATION_RETRIEVAL_PORT}
      CHATGPT_RESPONSE_PORT: ${CHATGPT_RESPONSE_PORT}
      POSTPROCESS_PORT: ${POSTPROCESS_PORT}
      TZ: ${TZ}
    depends_on:
      - redis-stack-server
